### ISSUE TITLE
Codice ISTAT del comune (pro_com_t)

### ISSUE THREAD

**Issue by dennisangemi** [italia/anpr-opendata#11]
Al fine di migliorare l'interoperabilità dei dati di questo repo, sarebbe possibile aggiungere una colonna contenente il codice istat del comune (`pro_com_t`) nel file [`popolazione_residente_export.csv`](https://github.com/italia/anpr-opendata/blob/main/data/popolazione_residente_export.csv)?

Aggiungendo tale codice, si potrebbe addirittura pensare di eliminare le colonne `REGIONE` e `PROVINCIA` perchè ridondanti.

Grazie!

**Comment by mfortini** [comment]
Aggiunto il codice istat come colonna

**Comment by dennisangemi** [comment]
Grazie @mfortini!

**Comment by aborruso** [comment]
Grazie
